version: '3.1'

services:
  cs4116-frontend:
    depends_on:
      - cs4116-php
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html:ro
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/certs/:/etc/nginx/ssl/live/localhost:ro

  # Optional basic scss support
  # scss:
  #   build:
  #     dockerfile: ./docker/scss.dockerfile
  #     context: .
  #   volumes:
  #     - ./scss:/scss:ro
  #     - ./src/generated-css:/css:rw

  cs4116-php:
    depends_on:
      - cs4116-mysql
    volumes:
      - ./src:/var/www/html:rw
    build:
      context: .
      dockerfile: docker/php.dockerfile

  cs4116-mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=cs4116
      - MYSQL_USER=cs4116
      - MYSQL_PASSWORD=cs4116
      - MYSQL_ROOT_PASSWORD=cs4116
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
