version: '3.1'

services:
  frontend:
    depends_on:
      - php
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./src:/var/www/html:ro
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/certs/:/etc/nginx/ssl/live/localhost:ro

  php:
    image: php:fpm-alpine
    volumes:
      - ./src:/var/www/html:ro

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=cs4116
      - MYSQL_USER=cs4116
      - MYSQL_PASSWORD=cs4116
      - MYSQL_ROOT_PASSWORD=cs4116
    volumes:
      - ./docker/mysql-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
